version: '3'

services:
  pokedexapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${APP_PORT}:${APP_PORT}"
    # working_dir: /var/www/pokedex
    environment:
      MONGODB_URI: ${MONGODB_URI}
      PORT: ${APP_PORT}
      PAGINATION_DEFAULT_LIMIT: ${PAGINATION_DEFAULT_LIMIT}
      PAGINATION_DEFAULT_OFFSET: ${PAGINATION_DEFAULT_OFFSET}
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: mongo:5
    container_name: mongo-poke
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: pokemonDB
    # volumes:
    #   - ./data/mongo:/data/db