version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: tesloDB
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data